In [1]:
!pip install -q bokeh

In [2]:
from bokeh.plotting import figure, show
import bokeh.io
import numpy as np

In [3]:
bokeh.io.output_notebook()

# 1 - Creating a line chart

In [4]:
x = np.arange(1, 11)
y = np.random.randint(10, 50, 10)

print(x, y)

[ 1  2  3  4  5  6  7  8  9 10] [32 20 44 29 36 31 30 35 14 33]


In [5]:
p = figure(title='My first plot with Bokeh', x_axis_label='X', y_axis_label='Y')

In [6]:
p.line(x, y, legend_label='Random numbers', line_width=2)

GlyphRenderer(id='1038', ...)

In [7]:
show(p)

In [8]:
y1 = np.random.randint(low=0, high=10, size=10)
y2 = np.random.randint(low=0, high=10, size=10)
y3 = np.random.randint(low=0, high=10, size=10)

In [9]:
p = figure(title='Multilines', x_axis_label='X', y_axis_label='Y')

In [10]:
p.line(x, y1, color='red', legend_label='Y1')
p.line(x, y2, color='blue', legend_label='Y2')
p.line(x, y3, color='green', legend_label='Y3')

GlyphRenderer(id='1185', ...)

In [11]:
show(p)

# 2 - Adding and customizing renderes

In [12]:
y1 = np.random.randint(low=1, high=5, size=10)
y2 = np.random.randint(low=6, high=10, size=10)
y3 = np.random.randint(low=1, high=10, size=10)

In [13]:
p = figure(title='Objects beyond lines', x_axis_label='X', y_axis_label='Y')

In [14]:
p.line(x, y1, color='green', legend_label='Between 1 and 5', line_width=2)
p.line(x, y2, color='blue', legend_label='Between 6 and 10', line_width=2)
p.circle(x, y3, color='red', legend_label='Circle time!', size=10)

GlyphRenderer(id='1369', ...)

In [15]:
show(p)

In [16]:
p = figure(title='Now... Bars', x_axis_label='X', y_axis_label='Y')

In [17]:
p.line(x, y1, color='green', legend_label='Between 1 and 5', line_width=2)
p.vbar(x=x, top=y2, bottom=0, color='blue', legend_label='Between 6 and 10', width=.25)
p.circle(x, y3, color='red', legend_label='Circle time!', size=10)

GlyphRenderer(id='1567', ...)

In [18]:
show(p)

## 2.1 - Customizing glyphs


In [19]:
y = np.random.randint(low=1, high=10, size=10)
s = np.random.randint(low=10, high=100, size=10)

In [20]:
print(y)
print(s)

[1 5 4 3 5 4 9 4 1 5]
[53 29 64 15 12 43 87 13 77 49]


In [21]:
p = figure(title='Custom circles', x_axis_label='X', y_axis_label='Y')

In [22]:
cicles = p.circle(x, y, size=s, legend_label='Variate size', fill_color='red', line_color='blue')

In [23]:
show(p)

In [24]:
cicles.glyph.fill_alpha = .5

In [25]:
show(p)

# 3 - Adding legends, text and annotations

In [26]:
years = np.arange(2000, 2021)
rate = np.absolute(np.log2(np.random.rand(21) * 10))
variance = np.absolute(np.log10(np.random.rand(21) * 100))


In [27]:
p = figure(title='Customizing text')

rate_plot = p.line(
    x=years,
    y=rate,
    legend_label='Rate',
    line_color='blue',
    line_width=2
)

variance_plot = p.line(
    x=years,
    y=variance,
    legend_label='Variance',
    line_color='red',
    line_width=2
)

In [28]:
show(p)

In [29]:
p.legend.title = 'Infos'
p.legend.title_text_font_style = 'bold'
p.legend.location = 'top_left'
p.legend.border_line_color = 'black'
p.legend.border_line_width = 1.5
p.legend.background_fill_color = 'black'
p.legend.background_fill_alpha = .2

In [30]:
show(p)

In [31]:
p.title_location = 'left'
p.title.text_color = 'purple'
p.title.text_font_size = '25pt'

In [32]:
show(p)

## 3.1 - Annotations

In [33]:
from bokeh.models import BoxAnnotation

In [34]:
print('Max variance', np.max(variance))
print('Min variance', np.min(variance))

Max variance 1.9517915787552955
Min variance 0.05324656830945757


In [35]:
print('Max rate', np.max(rate))
print('Min rate', np.min(rate))

Max rate 3.22320489529666
Min rate 1.1611985414409527


In [36]:
median_mav_mir = np.median([np.max(variance), np.min(rate)])

In [37]:
median_mar_miv = np.median([np.max(rate), np.min(variance)])

In [38]:
max_middle_annotation = np.max([median_mav_mir, median_mar_miv])
min_middle_annotation = np.min([median_mav_mir, median_mar_miv])

In [39]:
low_area = BoxAnnotation(
    top=min_middle_annotation,
    fill_alpha=0.2,
    fill_color='#F2AC29'
)
middle_area = BoxAnnotation(
    bottom=min_middle_annotation,
    top=max_middle_annotation,
    fill_alpha=0.2,
    fill_color='#5A5FBF'
)
high_area = BoxAnnotation(
    bottom=max_middle_annotation,
    fill_alpha=0.2,
    fill_color='#F2AC29'
)

In [40]:
p.add_layout(low_area)
p.add_layout(middle_area)
p.add_layout(high_area)

In [41]:
show(p)

# 4 - Custom plot

In [42]:
from bokeh.io import curdoc

In [43]:
curdoc().theme = 'dark_minimal'

In [44]:
x = np.arange(1, 11)
y = np.random.randint(low=0, high=10, size=10)

In [45]:
p = figure(sizing_mode='stretch_width', max_width=500, height=250)

p.line(x, y)

show(p)

In [46]:
curdoc().theme = None

In [47]:
z = np.abs(np.random.rand(10) * 100)

In [48]:
print(z)

[89.33852582 79.89469625 45.03945119 59.14997379 50.39930185 12.36137194
 93.92340868 43.37305267 50.75144926 18.13369149]


In [49]:
p = figure(
    title='Resizing',
    width=720,
    height=400,
    x_axis_label='X',
    y_axis_label='Y',
    y_range=(1, 10)
)

p.circle(
    x,
    y,
    size=z,
    fill_color='#DBF227',
    line_color=None,
    fill_alpha=0.3
)

show(p)

In [50]:
p.width = 500

show(p)

In [51]:
p.sizing_mode = 'stretch_width'
p.min_width = 50

show(p)

In [52]:
p.xaxis.axis_label = 'Width'
p.yaxis.axis_label = 'Height'

p.axis.axis_line_width = 5
p.axis.axis_line_color = 'black'

p.axis.major_label_text_color = 'black'
p.yaxis.major_label_orientation = 'vertical'

p.axis.minor_tick_in = 1
p.axis.minor_tick_out = 5
p.axis.major_tick_in = 1
p.axis.major_tick_out = 5
p.axis.major_tick_line_color = 'black'
p.axis.minor_tick_line_color = 'black'
p.axis.major_tick_line_width = 2
p.axis.minor_tick_line_width = 2

show(p)

In [53]:
from bokeh.models import NumeralTickFormatter

In [54]:
p.yaxis[0].formatter = NumeralTickFormatter(format="0 cm")
p.xaxis[0].formatter = NumeralTickFormatter(format="0 cm")

show(p)

In [55]:
x = [.1, .5, 1., 1.5, 2., 2.5, 3.]
y0 = np.power(2, x)
y1 = np.power(10, x)
y2 = np.power(10, y0)


print(y0)
print(y1)
print(y2)

[1.07177346 1.41421356 2.         2.82842712 4.         5.65685425
 8.        ]
[   1.25892541    3.16227766   10.           31.6227766   100.
  316.22776602 1000.        ]
[1.17970512e+01 2.59545535e+01 1.00000000e+02 6.73638848e+02
 1.00000000e+04 4.53789298e+05 1.00000000e+08]


In [56]:
p = figure(
    title="Logarithmic axis",
    sizing_mode="stretch_width",
    height=300,
    max_width=720,
    y_axis_type="log",
    y_range=[0.001, 10 ** 11],
    x_axis_label="sections",
    y_axis_label="particles",
)

p.line(x, x, legend_label="y=x")
p.circle(x, x, legend_label="y=x", fill_color="white", size=8)
p.line(x, y0, legend_label="y=x^2", line_width=3)
p.line(x, y1, legend_label="y=10^x", line_color="red")
p.circle(x, y1, legend_label="y=10^x", fill_color="red", line_color="red", size=6)
p.line(x, y2, legend_label="y=10^x^2", line_color="orange", line_dash="4 4")

p.legend.location = 'top_left'

show(p)

In [57]:
from datetime import datetime, timedelta

from bokeh.models import DatetimeTickFormatter

In [58]:
date = [(datetime.now() + timedelta(day * 7)) for day in range(0, 50)]

y = np.random.sample(50) * 100

print(y)

[87.74697508 59.87655563 81.87369598 83.16741141 27.02131815 95.90977391
 80.05503309 66.38156195 80.88248054 13.34659487 35.04955748 79.14762832
 65.7053499  20.56197098 75.04539989 82.43805017 15.70010142 55.55855875
 25.28834228 10.49123922 16.9716045  84.83838657  9.48879975 51.65810496
 66.45246038 16.1542715  80.96575757 65.58368618 19.91740742 42.19011186
 96.94075039 85.47569469 17.14590889 51.64739537 59.48032318 94.8625254
 29.12095711 26.37502322 69.17913453 36.32996013 38.50866421 66.37916715
 72.35523692 37.81137882 33.90993878 11.69803052 49.87155267 81.43840587
 15.50383853 58.51902168]


In [59]:
curdoc().theme = None

In [60]:
p = figure(
    title="Datetime Axis",
    x_axis_type="datetime",
    sizing_mode="stretch_width",
    max_width=720,
    height=300,
)

p.circle(date, y, size=8)
p.line(date, y, color="navy", line_width=1)

p.yaxis[0].formatter = NumeralTickFormatter(format='R$0.00')
p.xaxis[0].formatter = DatetimeTickFormatter(months='%b %Y')

show(p)

In [61]:
x = [1, 2, 3, 4, 5]
y = np.random.randint(low=1, high=10, size=5)

In [62]:
p = figure(
    title='Custom grid',
    sizing_mode='stretch_width',
    max_width=500,
    height=250
)

p.line(x, y, line_color='green', line_width=2)

p.xgrid.grid_line_color = 'red'

p.ygrid.grid_line_alpha = 1
p.ygrid.grid_line_dash = [5, 4, 3]

show(p)

In [63]:
p.ygrid.band_fill_color = 'olive'
p.ygrid.band_fill_alpha = .1

p.xgrid.bounds = (2, 4)

show(p)

In [64]:
p.background_fill_color = (127, 255, 127)
p.border_fill_color = (64, 64, 127)
p.outline_line_color = (0, 0, 255)

show(p)

In [65]:
p.toolbar_location = 'left'

show(p)

In [66]:
p.toolbar.autohide = True

show(p)

In [67]:
p.toolbar.autohide = False

In [68]:
from bokeh.models.tools import BoxZoomTool, ResetTool

In [69]:
p.tools = [BoxZoomTool(), ResetTool()]

show(p)

In [70]:
from bokeh.models.tools import PanTool

In [71]:
p.add_tools(PanTool(dimensions='width'))

show(p)

In [72]:
p.circle(x, y, color='green', size=10)

GlyphRenderer(id='4763', ...)

In [73]:
from bokeh.models import HoverTool

In [74]:
hover_tool = HoverTool()

In [75]:
hover_tool.tooltips = [
                       ('@x', '$y')
]

In [76]:
p.add_tools(hover_tool)

In [77]:
show(p)

# 5 - Vectorizing glyph properties

In [78]:
x = np.arange(0, 30)
y = np.random.randint(low=0, high=100, size=30)

In [79]:
print(y)

[60  8 98  7 66 87 57 72 90 97 28  5 22 42 79 30 40 74 12 16 31 20 13 39
  8 31 70 63 93 92]


In [80]:
colors = ['#{0:x}{1:0>2x}{2:x}'.format(127, int(round(value * 255 / 100)), 255) for value in y]

In [81]:
print(colors)

['#7f99ff', '#7f14ff', '#7ffaff', '#7f12ff', '#7fa8ff', '#7fdeff', '#7f91ff', '#7fb8ff', '#7fe6ff', '#7ff7ff', '#7f47ff', '#7f0dff', '#7f38ff', '#7f6bff', '#7fc9ff', '#7f4cff', '#7f66ff', '#7fbdff', '#7f1fff', '#7f29ff', '#7f4fff', '#7f33ff', '#7f21ff', '#7f63ff', '#7f14ff', '#7f4fff', '#7fb2ff', '#7fa1ff', '#7fedff', '#7febff']


In [82]:
p = figure(
    title='Custom color',
    sizing_mode='stretch_width',
    max_width=500,
    height=250,
)

In [83]:
line = p.line(x, y, line_color='blue', line_width=1)
circle = p.circle(x, y, fill_color=colors, line_color='blue', size=15)

In [84]:
show(p)

In [85]:
N = 1000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100

In [86]:
radii = np.multiply(np.divide(y, 100), 2)
colors = ['#{0:x}{1:0>2x}{2:x}'.format(127, int(round(value * 255 / 100)), 255) for value in y]

In [87]:
p = figure(
    title='Custom color',
    sizing_mode='stretch_width',
    max_width=500,
    height=250,
)

circle = p.circle(
    x,
    y,
    radius=radii,
    fill_color=colors,
    size=15,
    fill_alpha=.7,
    line_color='lightgrey'
)

In [88]:
show(p)

In [89]:
from bokeh.palettes import Turbo256
from bokeh.transform import linear_cmap

In [90]:
x = np.arange(-32, 33)
y = [-1 * np.power(i, 2) for i in x]

mapper = linear_cmap(field_name='y', palette=Turbo256, low=np.min(y), high=np.max(y))

p = figure(width=500, height=250)

p.circle(x, y, color=mapper, size=10)

GlyphRenderer(id='5677', ...)

In [91]:
show(p)

# 6 - Comibing plots

In [92]:
from bokeh.layouts import row

In [93]:
x = np.arange(11)
y0 = x
y1 = [len(x) - i for i in x]
y2 = np.absolute(np.subtract(x, 5))

In [94]:
def small_square_fig():
    return figure(width=250, height=250)

In [95]:
s1 = small_square_fig()
s1.circle(x, y0, size=12, color='#05AFE3', fill_alpha=.6)

s2 = small_square_fig()
s2.triangle(x, y1, size=12, color='#EDCA20', fill_alpha=.6)

s3 = small_square_fig()
s3.square(x, y2, size=12, color='#F54248', fill_alpha=.6)

GlyphRenderer(id='6022', ...)

In [96]:
show(row(s1, s2, s3))

In [97]:
show(row(children=[s1, s2, s3], sizing_mode='scale_width'))

# 7 - Displaying and exporting

In [98]:
from bokeh.plotting import output_file, save

In [99]:
bokeh.io.output_file('plot.html', title='My Plot')

In [100]:
output_file(filename='plot.html', title='My file')

In [101]:
save(row(children=[s1, s2, s3], sizing_mode='scale_width'))

RuntimeError: ignored

# 8 - Providing and filtering data

In [102]:
from bokeh.models import ColumnDataSource

In [103]:
data = {
    'x_dim': [1, 2, 3, 4, 5, 6, 7, 8, 9],
    'y_dim': np.random.randint(low=1, high=10, size=9)
}

In [104]:
source = ColumnDataSource(data=data)

In [109]:
p = figure()

p.circle(x='x_dim', y='y_dim', source=source, size=10)

GlyphRenderer(id='7841', ...)

In [110]:
show(p)

In [111]:
from bokeh.models import CDSView, IndexFilter

In [115]:
from bokeh.layouts import gridplot

In [117]:
view = CDSView(source=source, filters=[IndexFilter([0, 2, 4, 6, 8])])

In [118]:
tools = ['box_select', 'hover', 'reset']

p = figure(height=300, width=300, tools=tools)
p.circle(x='x_dim', y='y_dim', size=10, hover_color='red', source=source)

p_filtered = figure(height=300, width=300, tools=tools)
p_filtered.circle(x='x_dim', y='y_dim', size=10, hover_color='red', source=source, view=view)

GlyphRenderer(id='9093', ...)

In [119]:
show(gridplot([[p, p_filtered]]))